// Quiz title mapping - maps filename to display title
export const QUIZ_TITLES: { [key: string]: string } = {
  'AfricanHistory': 'African History',
  'AmericanHistory': 'American History',
  'AmericanRevolution': 'American Revolution',
  'Amphibians': 'Amphibians',
  'AncientChina': 'Ancient China',
  'AncientEgypt': 'Ancient Egypt',
  'AncientGreece': 'Ancient Greece',
  'AncientHistory': 'Ancient History',
  'Animals': 'Animals',
  'Architecture': 'Architecture',
  'Art': 'Art',
  'AsianHistory': 'Asian History',
  'Astronomy': 'Astronomy',
  'Biology': 'Biology',
  'Birds': 'Birds',
  'Books': 'Books',
  'Capitals': 'Capitals',
  'Chemistry': 'Chemistry',
  'Cities': 'Cities',
  'CivilWar': 'Civil War',
  'ClassicLiterature': 'Classic Literature',
  'Clouds': 'Clouds',
  'Colors': 'Colors',
  'ColorsAdvanced': 'Advanced Colors',
  'Composers': 'Composers',
  'Computers': 'Computers',
  'Conservation': 'Conservation',
  'Continents': 'Continents',
  'Countries': 'Countries',
  'Currency': 'Currency',
  'Dinosaurs': 'Dinosaurs',
  'DisneyAnimation': 'Disney Animation',
  'DisneyAttractions': 'Disney Attractions',
  'DisneyCharacters': 'Disney Characters',
  'DisneyCompany': 'Disney Company',
  'DisneyHistory': 'Disney History',
  'DisneyMovies': 'Disney Movies',
  'DisneyMusic': 'Disney Music',
  'DisneyParks': 'Disney Parks',
  'DisneyPrincesses': 'Disney Princesses',
  'DisneyVillains': 'Disney Villains',
  'Earthquakes': 'Earthquakes',
  'Ecosystems': 'Ecosystems',
  'Emotions': 'Emotions',
  'Energy': 'Energy',
  'EuropeanHistory': 'European History',
  'Explorers': 'Explorers',
  'Fish': 'Fish',
  'Flags': 'Flags',
  'Flowers': 'Flowers',
  'Food': 'Food',
  'Forces': 'Forces',
  'Fruits': 'Fruits',
  'Games': 'Games',
  'GardeningBasics': 'Gardening Basics',
  'GardeningFlowers': 'Gardening: Flowers',
  'GardeningHerbs': 'Gardening: Herbs',
  'GardeningTips': 'Gardening Tips',
  'GardeningVegetables': 'Gardening: Vegetables',
  'Geography': 'Geography',
  'GolfBasics': 'Golf Basics',
  'GolfCourses': 'Golf Courses',
  'GolfEquipment': 'Golf Equipment',
  'GolfEtiquette': 'Golf Etiquette',
  'GolfHistory': 'Golf History',
  'GolfMajors': 'Golf Majors',
  'GolfPlayers': 'Golf Players',
  'GolfRules': 'Golf Rules',
  'GolfScoring': 'Golf Scoring',
  'GolfTips': 'Golf Tips',
  'GreekMythology': 'Greek Mythology',
  'Habitats': 'Habitats',
  'Holidays': 'Holidays',
  'HumanBody': 'Human Body',
  'Insects': 'Insects',
  'Internet': 'Internet',
  'Inventions': 'Inventions',
  'Islands': 'Islands',
  'Languages': 'Languages',
  'LatinAmericanHistory': 'Latin American History',
  'Light': 'Light',
  'Machines': 'Machines',
  'Mammals': 'Mammals',
  'Materials': 'Materials',
  'Mathematics': 'Mathematics',
  'Measurement': 'Measurement',
  'MedievalEurope': 'Medieval Europe',
  'MedievalHistory': 'Medieval History',
  'MiddleAges': 'Middle Ages',
  'Months': 'Months',
  'Mountains': 'Mountains',
  'Movies': 'Movies',
  'Music': 'Music',
  'Mythology': 'Mythology',
  'MythsAndLegends': 'Myths and Legends',
  'NFLDraft': 'NFL Draft',
  'NFLHistory': 'NFL History',
  'NFLPlayers': 'NFL Players',
  'NFLPlayoffs': 'NFL Playoffs',
  'NFLPositions': 'NFL Positions',
  'NFLRecords': 'NFL Records',
  'NFLRules': 'NFL Rules',
  'NFLStats': 'NFL Statistics',
  'NFLSuperBowl': 'NFL Super Bowl',
  'NFLTeams': 'NFL Teams',
  'NurseryRhymes': 'Nursery Rhymes',
  'Oceans': 'Oceans',
  'Olympics': 'Olympics',
  'Physics': 'Physics',
  'PiratesCaribbean': 'Pirates: Caribbean',
  'PiratesFamous': 'Famous Pirates',
  'PiratesFiction': 'Pirates in Fiction',
  'PiratesGeneral': 'Pirates',
  'PiratesLife': 'Pirate Life',
  'PiratesModern': 'Modern Pirates',
  'PiratesMyths': 'Pirate Myths',
  'PiratesShips': 'Pirate Ships',
  'PiratesTreasure': 'Pirate Treasure',
  'PiratesWeapons': 'Pirate Weapons',
  'Planets': 'Planets',
  'Plants': 'Plants',
  'Poetry': 'Poetry',
  'Presidents': 'U.S. Presidents',
  'PresidentsAchievements': 'Presidential Achievements',
  'PresidentsAssassinations': 'Presidential Assassinations',
  'PresidentsEarly': 'Early Presidents',
  'PresidentsElections': 'Presidential Elections',
  'PresidentsFirsts': 'Presidential Firsts',
  'PresidentsGeneral': 'Presidents General',
  'PresidentsLegacy': 'Presidential Legacy',
  'PresidentsModern': 'Modern Presidents',
  'PresidentsPersonal': 'Presidential Personal Life',
  'PresidentsQuotes': 'Presidential Quotes',
  'PresidentsWars': 'Presidents and Wars',
  'Renaissance': 'Renaissance',
  'RenaissanceHistory': 'Renaissance History',
  'Reptiles': 'Reptiles',
  'Rivers': 'Rivers',
  'RomanBuildings': 'Roman Buildings',
  'RomanCulture': 'Roman Culture',
  'RomanDailyLife': 'Roman Daily Life',
  'RomanEmperors': 'Roman Emperors',
  'RomanEmpire': 'Roman Empire',
  'RomanFall': 'Fall of Rome',
  'RomanLegacy': 'Roman Legacy',
  'RomanMilitary': 'Roman Military',
  'RomanRepublic': 'Roman Republic',
  'RomanWars': 'Roman Wars',
  'Seas': 'Seas',
  'Seasons': 'Seasons',
  'SeasonsAdvanced': 'Advanced Seasons',
  'Senses': 'Senses',
  'Shakespeare': 'Shakespeare',
  'Shapes': 'Shapes',
  'Sound': 'Sound',
  'Space': 'Space',
  'Sports': 'Sports',
  'Stars': 'Stars',
  'StateCapitals': 'State Capitals',
  'StateFacts': 'State Facts',
  'StateFlags': 'State Flags',
  'StateGeography': 'State Geography',
  'StateHistory': 'State History',
  'StateNicknames': 'State Nicknames',
  'StateRecords': 'State Records',
  'StateSymbols': 'State Symbols',
  'StateTrivia': 'State Trivia',
  'States': 'U.S. States',
  'StatesGeneral': 'States General',
  'Technology': 'Technology',
  'Time': 'Time',
  'TimeZones': 'Time Zones',
  'Transportation': 'Transportation',
  'Trees': 'Trees',
  'Vegetables': 'Vegetables',
  'Volcanoes': 'Volcanoes',
  'WaterCycle': 'Water Cycle',
  'Weather': 'Weather',
  'WeatherAdvanced': 'Advanced Weather',
  'Weekdays': 'Weekdays',
  'WeirdFoodBans': 'Weird Food Bans',
  'WeirdFoodBeliefs': 'Weird Food Beliefs',
  'WeirdFoodCurrency': 'Food as Currency',
  'WeirdFoodFacts': 'Weird Food Facts',
  'WeirdFoodHistory': 'Weird Food History',
  'WeirdFoodInventions': 'Weird Food Inventions',
  'WeirdFoodLuxury': 'Food as Luxury',
  'WeirdFoodMedicine': 'Food as Medicine',
  'WeirdFoodMyths': 'Weird Food Myths',
  'WeirdFoodOrigins': 'Weird Food Origins',
  'WorldGeography': 'World Geography',
  'WorldWarI': 'World War I',
  'WorldWarIAftermath': 'World War I Aftermath',
  'WorldWarIBattles': 'World War I Battles',
  'WorldWarICauses': 'World War I Causes',
  'WorldWarII': 'World War II',
  'WorldWarIIAftermath': 'World War II Aftermath',
  'WorldWarIIBattles': 'World War II Battles',
  'WorldWarIITimeline': 'World War II Timeline',
  'WorldWarsComparison': 'World Wars Comparison',
  'WorldWarsTechnology': 'World Wars Technology',
  'MarineBiology': 'Marine Biology',
  'Genetics': 'Genetics',
  'Evolution': 'Evolution',
  'ClimateChange': 'Climate Change',
  'Geology': 'Geology',
  'Meteorology': 'Meteorology',
  'Botany': 'Botany',
  'Zoology': 'Zoology',
  'Microbiology': 'Microbiology',
  'Neuroscience': 'Neuroscience',
  'QuantumPhysics': 'Quantum Physics',
  'ChemistryAdvanced': 'Advanced Chemistry',
  'Anatomy': 'Anatomy',
  'Physiology': 'Physiology',
  'Ecology': 'Ecology',
  'Paleontology': 'Paleontology',
  'Astrophysics': 'Astrophysics',
  'Oceanography': 'Oceanography',
  'Biochemistry': 'Biochemistry',
  'Pharmacology': 'Pharmacology',
  'Basketball': 'Basketball',
  'Baseball': 'Baseball',
  'Soccer': 'Soccer',
  'Tennis': 'Tennis',
  'Hockey': 'Hockey',
  'OlympicGames': 'Olympic Games',
  'Boxing': 'Boxing',
  'Swimming': 'Swimming',
  'TrackAndField': 'Track and Field',
  'Cycling': 'Cycling',
  'Skiing': 'Skiing',
  'Surfing': 'Surfing',
  'Cricket': 'Cricket',
  'Rugby': 'Rugby',
  'Volleyball': 'Volleyball',
  'MarvelMovies': 'Marvel Movies',
  'StarWars': 'Star Wars',
  'HarryPotter': 'Harry Potter',
  'LordOfTheRings': 'Lord of the Rings',
  'GameOfThrones': 'Game of Thrones',
  'TheOffice': 'The Office',
  'Friends': 'Friends',
  'BreakingBad': 'Breaking Bad',
  'StrangerThings': 'Stranger Things',
  'MusicGenres': 'Music Genres',
  'RockMusic': 'Rock Music',
  'HipHop': 'Hip Hop',
  'Jazz': 'Jazz',
  'ClassicalMusic': 'Classical Music',
  'CountryMusic': 'Country Music',
  'AncientRome': 'Ancient Rome',
  'Vikings': 'Vikings',
  'MedievalKnights': 'Medieval Knights',
  'RenaissanceArt': 'Renaissance Art',
  'IndustrialRevolution': 'Industrial Revolution',
  'ColdWar': 'Cold War',
  'VietnamWar': 'Vietnam War',
  'KoreanWar': 'Korean War',
  'FrenchRevolution': 'French Revolution',
  'RussianRevolution': 'Russian Revolution',
  'AncientMesopotamia': 'Ancient Mesopotamia',
  'MayanCivilization': 'Mayan Civilization',
  'IncaEmpire': 'Inca Empire',
  'AztecEmpire': 'Aztec Empire',
  'ByzantineEmpire': 'Byzantine Empire',
  'EuropeanCountries': 'European Countries',
  'AsianCountries': 'Asian Countries',
  'AfricanCountries': 'African Countries',
  'SouthAmericanCountries': 'South American Countries',
  'NorthAmericanCountries': 'North American Countries',
  'Deserts': 'Deserts',
  'Rainforests': 'Rainforests',
  'ShakespearePlays': 'Shakespeare Plays',
  'PoetryFamous': 'Famous Poetry',
  'Novels': 'Novels',
  'ScienceFiction': 'Science Fiction',
  'Fantasy': 'Fantasy',
  'Mystery': 'Mystery',
  'Horror': 'Horror',
  'Romance': 'Romance',
  'Biographies': 'Biographies',
  'MythologyNorse': 'Norse Mythology',
  'ArtificialIntelligence': 'Artificial Intelligence',
  'Cryptocurrency': 'Cryptocurrency',
  'Programming': 'Programming',
  'VideoGames': 'Video Games',
  'SocialMedia': 'Social Media',
  'InternetHistory': 'Internet History',
  'MobileApps': 'Mobile Apps',
  'Cybersecurity': 'Cybersecurity',
  'Robotics': 'Robotics',
  'VirtualReality': 'Virtual Reality',
  'CookingBasics': 'Cooking Basics',
  'WorldCuisines': 'World Cuisines',
  'Baking': 'Baking',
  'Wine': 'Wine',
  'Coffee': 'Coffee',
  'USStatesAndCapitals': 'US States and Capitals',
  'WorldCountriesAndCapitals': 'World Countries and Capitals',
};

// Helper function to get title from filename
export const getQuizTitle = (filename: string): string => {
  return QUIZ_TITLES[filename] || filename.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()).trim();
};

